# source package files for temporary development
Rpath <- '../R'
source(paste(Rpath, 'Node.R', sep='/'))
source(paste(Rpath, 'LeafNode.R', sep='/'))
source(paste(Rpath, 'ChanceNode.R', sep='/'))
source(paste(Rpath, 'DecisionNode.R', sep='/'))
source(paste(Rpath, 'Edge.R', sep='/'))
source(paste(Rpath, 'Path.R', sep='/'))
source(paste(Rpath, 'ModelVariable.R', sep='/'))
source(paste(Rpath, 'ConstModelVariable.R', sep='/'))
source(paste(Rpath, 'BetaModelVariable.R', sep='/'))
source(paste(Rpath, 'GammaModelVariable.R', sep='/'))
source(paste(Rpath, 'NormalModelVariable.R', sep='/'))
source(paste(Rpath, 'LogNormalModelVariable.R', sep='/'))
source(paste(Rpath, 'ExpressionModelVariable.R', sep='/'))
