---
title: "Untitled"
author: "Andrew"
date: "08/02/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r drawing, echo=FALSE, results='hide', fig.align='center', fig.keep='last'}

vp <- grid::viewport(
  x = grid::unit(0,"snpc"), y = grid::unit(0,"snpc"),
  width = grid::unit(4.0, "snpc"), height=grid::unit(1.0,"snpc"),
  just = c("left", "bottom")
)

grid::grid.circle(
  x = grid::unit(0.5,"snpc"), y = grid::unit(0.5, "snpc"),
  r = grid::unit(0.25,"snpc"),
  gp = grid::gpar(col="red"),
  vp = vp
)

grid::grid.rect(
  x = grid::unit(0.0,"snpc"), y = grid::unit(0.0,"snpc"),
  width = grid::unit(0.25,"snpc"), height = grid::unit(0.5,"snpc"),
  just = c("left", "bottom"),
  gp = grid::gpar(col="blue")
)

grid::grid.rect(
  x = grid::unit(0.5,"snpc"), y = grid::unit(0.5,"snpc"),
  width = grid::unit(1.0,"snpc"), height = grid::unit(1.0,"snpc"),
  gp = grid::gpar(col="green")
)

grid::grid.rect(
  x = grid::unit(0,"snpc"), y = grid::unit(0,"snpc"),
  width = grid::unit(4.0,"snpc"), height = grid::unit(0.25,"snpc"),
  just = c("left", "bottom"),
  gp = grid::gpar(col="orange")
)

grid::pushViewport(vp)
grid::popViewport()
```